esphome:
  name: chaudiere
  friendly_name: Chaudiere

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EKxzfU14OtyT1DxeBQlZSIMZGsYJuLzXlF/GQyEQHBg="

ota:
  password: "6b4ba4cb938419a46ca9b563d8f537cb"

wifi:
  networks:
    - ssid: !secret wifi_ssid_bureau
      password: !secret wifi_password_bureau
    - ssid: !secret wifi_ssid_maison
      password: !secret wifi_password_maison

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Chaudiere Fallback Hotspot"
    password: "yf081j14Sopt"

captive_portal:
    
switch:
  - platform: gpio
    pin: 05
    name: "Circulateur ON/OFF"
