esphome:
  name: temp-int
  friendly_name: temp int

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3P6sPCkx8sCXNISWKtE885SNEX6WJXyWJIsLUuoOo6o="

ota:
  password: "95ad273a7063ee7edc9517fa97a1d289"

wifi:
  networks:
    - ssid: !secret wifi_ssid_bureau
      password: !secret wifi_password_bureau
    - ssid: !secret wifi_ssid_maison
      password: !secret wifi_password_maison

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp-Int Fallback Hotspot"
    password: "OaLIp6joHZZM"

captive_portal:
    

sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s